export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL

export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

export const VALID_ALPHABET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

export const VALID_ALPHABET_LENGTH = 8
